### ISSUE TITLE
Publish the document to TR

### ISSUE THREAD

**Issue by kenchris** [w3c/manifest-app-info#11]
So that https://w3c.github.io/manifest-app-info works

**Comment by marcoscaceres** [comment]
Once we publish, we will enable auto-publish directly to TR. So we shouldn't need gh-pages 🤞

**Comment by aarongustafson** [comment]
@marcoscaceres created a temporary `gh-pages` branch while we gather feedback. Once we set up auto-publish in a week or so, we can delete it and maintain the `main` branch moving forward.

**Comment by marcoscaceres** [comment]
As mentioned in #14 ... we might be stuck with gh-pages until Github overcomes their limitation of allowing another branch to serve as the GH Pages branch:(

**Comment by siusin** [comment]
AutoPub works now -> https://www.w3.org/TR/manifest-app-info/

Thanks @marcoscaceres !
