### ISSUE TITLE
Typo? at §2

### ISSUE THREAD

**Issue by ntounsi** [w3c/manifest-app-info#17]
At [section 2](https://www.w3.org/TR/2020/NOTE-manifest-app-info-20200730/#supplementary-manifest-members), after Example-1
"As the application manifest is JSON, *this* the members of this specification are of the types object, array, and string as defined in The JSON Data Interchange Format."

I am far from being good at English, but wouldn't there be one extra "this"?

**Comment by marcoscaceres** [comment]
You are right. Typo :) Will fix.
