### ISSUE TITLE
Definition of supplementary manifest members overriding the core manifest

### ISSUE THREAD

**Issue by espinr** [w3c/manifest-app-info#18]
Hi,
I'm trying to understand the [extensibility of the manifest](https://www.w3.org/TR/appmanifest/#extensibility) to help in the convergence of MiniApps to WebApps (related to w3c/miniapp#94) and I think this App-Info is the first example of extension. My question is about the [supplementary manifest members section](https://w3c.github.io/manifest-app-info/#supplementary-manifest-members), that describes attributes like `description` or `categories` that are already present in the core manifest. Is this correct?

I read in the spec that "When specifying a new member, don't override or monkey patch anything defined in this specification." In this case, I see that all four members are in the core manifest. I'm sorry if I missed something. Thanks in advance.

**Comment by aarongustafson** [comment]
@espinr These members will be removed from the Manifest and defined here instead. Just waiting on a PR merge: https://github.com/w3c/manifest/pull/924
