### ISSUE TITLE
Should platform value "chromeos" be "cros" or what does the Googler's prefer?

### ISSUE THREAD

**Issue by kenchris** [w3c/manifest-app-info#21]
@mgiuca @slightlyoff

**Comment by tomayac** [comment]
I'm not "Google", just speaking as a regular user: IMHO it should be an as descriptive as possible string like "Chrome OS" or "ChromeOS" (or lowercased).

**Comment by kenchris** [comment]
This url https://www.google.com/chromebook/chrome-os/ uses "chrome-os" so maybe "chrome-os"

**Comment by mgiuca** [comment]
Where is this listed? I don't see it in the Manifest spec or https://github.com/w3c/manifest/wiki/Platforms

What would it be used for? I think of "platforms" as app platforms, not operating systems. So we don't have a concept of a "Chrome OS app", we just have web apps and Android apps.

If we do need a string for Chrome OS somewhere, I would prefer "`chromeos`" which is the [ID that we use for the OS build target](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/chromeos_build_instructions.md#common-setup) in the code.

**Comment by kenchris** [comment]
https://www.w3.org/TR/manifest-app-info/#platform-member

**Comment by aarongustafson** [comment]
I think we can keep it as "chromeos" then.
