### ISSUE TITLE
Underscores in JSON values (not member fields) should be hyphen according to TAG style guide

### ISSUE THREAD

**Issue by kenchris** [w3c/manifest-app-info#22]
This means that "chrome_web_store" should be renamed "chrome-web-store" but maybe the Googler's prefer another name? @slightlyoff

**Comment by kenchris** [comment]
This url https://chrome.google.com/webstore uses "webstore" so maybe "chrome-webstore"

**Comment by tomayac** [comment]
I usually go by the `<title>` when I have to name things in articles etc. It looks like `chrome-web-store` is the more accurate representation.

**Comment by aarongustafson** [comment]
Per @mgiuca’s [comment about the `platform` key](https://github.com/w3c/manifest-app-info/issues/25#issuecomment-770533880), if we remove that this issue goes away, right?

**Comment by kenchris** [comment]
Right
