### ISSUE TITLE
Should we request TAG review for the Manifest App Info draft?

### ISSUE THREAD

**Issue by beverloo** [w3c/manifest-app-info#27]
Hi Aaron, others,

Wondering about your thoughts on the right timing and scope for requesting a TAG review on the draft 😃. Chrome is interested in beginning experimentation with the `description` and `screenshots` fields on Android, but I'm not fully aware of where you see the draft heading to know whether requesting a review right now would be the right thing to do.

**Comment by aarongustafson** [comment]
I believe all of the current members of this spec were part of the manifest spec when it went to TAG, so I am not sure we’d need it yet, but maybe @marcoscaceres or @kenchris have different thoughts.

**Comment by kenchris** [comment]
Yeah, it's probably covered already.

**Comment by marcoscaceres** [comment]
Agree. No need for a tag review for this as it was previously covered.

**Comment by beverloo** [comment]
Works for me, thank you for the thoughts! 👍
