### ISSUE TITLE
APA request for clarification of Label accessibility

### ISSUE THREAD

**Issue by becka11y** [w3c/manifest-app-info#29]
As part of an APA horizontal review, Paul Grenier reviewed the Application Information Working Group Note and made the following suggestions that have been approved by the APA working group. APA appreciates your consideration of accessibility in the note and is just seeking clarification. 

1. In label, https://www.w3.org/TR/manifest-app-info/#label-member, this statement "For accessibility, authors are encouraged to provide a label for each screenshot." To help guide implementers, I would suggest adding a hint how this could be accomplished, "For example, most web applications could use the page title or main heading (h1) as the screenshot label."
   2. While the label acts as an accessible name, in this case, a short description of the view, it might be helpful to include an accessible description <https://www.w3.org/TR/wai-aria-1.1/#dfn-accessible-description> supplementary information. This could be included for AT users to uncover a full description of the screenshot. While not needed in most cases, it would be especially helpful for specialized apps or apps targeting a disabled audience. In "app stores" this could appear as a visible link to an additional description.

**Comment by aarongustafson** [comment]
Thanks for this @becka11y!

1. Has an associated PR showing an example of how folx should do this and clarification as to how implementors should use the field. Let me know if you have additional concerns.
2. I’m on the fence about adding an additional `description` field as I would prefer folx properly apply alt text to the images using `label` first. If we see a need for longer descriptions, we can add an additional field later. These are just screenshots for display in installation dialogs and catalog pages, so there’s really not a need for incredible detail. My gut says `alt` text should suffice.

**Comment by johnfoliot** [comment]
Also related: https://github.com/w3c/image-resource/issues/39

**Comment by aarongustafson** [comment]
As I haven’t heard back, I believe this is resolved. I am going to close, but please re-open if you think there are additional items we need to address.
