### ISSUE TITLE
Request for additional categories

### ISSUE THREAD

**Issue by filips123** [w3c/manifest-app-info#37]
I think few other categories should be added to a list of known ones:

* `development`: Similar category (Developer Tools) already exists on macOS and Windows stores, but I have chosen "development" because it is just a single word to make it consistent with existing categories. This could include websites/apps that provide anything development-related, for example, VCS, IDEs, bug trackers, additional development utilities...

* `video`: macOS and Windows stores currently have the photo and video category joined while manifest only supports the photo category. This means video-only websites/apps (maybe like YouTube) have to specify a wrong category (photo) to get the correct store category. Adding a separate video category solves this issue and also allows stores with separate video and photo categories to take advantage of that.

* `design`: macOS store has Graphics & Design category and Windows store has Multimedia Design. This could include all graphical and multimedia design tools.

* `reference`: macOS store has this as a separate category, but Windows store has it joined with books. I think it would be useful to separate them in the manifest because the books category seems to be more for providing utilities to content that is normally printed while reference is more for providing knowledge and information (according to macOS category description).

* `network`: This one isn't on macOS and Windows stores, but I think it would be useful to have some category for all network, internet, and web-related apps. For example, clients for various network services, internet-related tools, etc. Some of them could be paired with existing categories to describe the app even better (for example, development and network to descript network-related developer tools).

It could be useful to also describe all categories listed in the specification but I think that is out-of-scope for this issue.

**Comment by jcayzac** [comment]
Our platform also has the following categories:

- `beauty`
- `car`
- `dating`
- `developer` this is the same as `development` in Filip's message.
- `events`
- `graphics` this is the same as `design` in Filip's message.
- `parenting`
- `pets`
- `reference` agree with Filip. Dictionary apps, wikis, interactive encyclopedias etc aren't books.

Also, from the existing list, I'm not sure exactly what's the difference between `donations` and `fundraising`.

**Comment by aarongustafson** [comment]
I will work on a PR to add these shortly.

**Comment by aarongustafson** [comment]
To be clear, the list is not exhaustive, nor is it limiting in any way. Most of these feel clear-cut. "networking" is a subcategory of "utilities," and as it doesn’t currently exist as a category, I’m leaving it out.

I’m tracking a few comments here for anyone who cares:

* "cars" feels overly specific, I’d suggest "transportation" instead, which is distinct from "travel" but gives leeway to house apps about motorcycles, boats, and other means of transporting us from one place to another.
* "beauty," on the other hand, feels a little vague. It feels like it might align more closely with "fashion" (which I’ve added as well). Related: "health" also exists and is often connected with "beauty" in stores & such.
* "video" (except for editing tools) would probably fall nicely in "entertainment" as well.
