### ISSUE TITLE
Ribbons

### ISSUE THREAD

**Issue by jcayzac** [w3c/manifest-app-info#45]
To support differentiating prerelease versions of apps (installed from a different URL), Rakuten supports overlaying a ribbon on top of a PWA's shortcut. For example,

![pwa-ribbons](https://user-images.githubusercontent.com/106682/136485872-4921a394-5d26-4677-a640-9c43022a0f9d.png)

The feature is supported by the following additions to the web manifest:

```webidl
partial interface WebAppManifest {
  attribute Ribbon? ribbon;
};

interface Ribbon {
  attribute USVString text;
  attribute USVString? text_color;
  attribute USVString? color;
};
```

`color` and  `text_color` are both processed according to [Web Application Manifest » §1.17.2 Processing color members](https://w3c.github.io/manifest/#dfn-process-a-color-member). Our platform provides default values when these attributes are omitted.

Is this something others in the working group would be interested in standardizing? If so, I could send a PR @aarongustafson @marcoscaceres

**Comment by marcoscaceres** [comment]
So... ok to close this @jcayzac?
