### ISSUE TITLE
consider ranaming "platform"

### ISSUE THREAD

**Issue by philloooo** [w3c/manifest-app-info#55]
"platform" is also used in the [manifest spec](https://www.w3.org/TR/appmanifest/#platform-member) and has different semantics. 

"narrow" or "wide" also isn't exactly a platform.

How about renaming it to "target"? Or any other better suggestions here?

**Comment by philloooo** [comment]
@aarongustafson what do you think?

**Comment by tomayac** [comment]
How about `"form_factor"`?

**Comment by philloooo** [comment]
that sounds better than platform, @dominickng WDYT?

**Comment by dominickng** [comment]
`form_factor` is definitely better than `platform`. :)

**Comment by aarongustafson** [comment]
My original thought had been to have "narrow" and "wide" as generic platform values that could represent a class of platforms.

I’m not against introducing a `form_factor` key but that does increase the complexity a little. Following that line of thought, we could disambiguate to `platform` for the OS and `form_factor` for the rendering. I think there’s merit in both, especially if there are differences, but at the same time, I do tend to favor simplicity.

**Comment by philloooo** [comment]
I think disambiguate to `platform` for OS and `form_factor` for rendering is better.
 
then IMO `platform` is kind of an anti-pattern for the manifest though, as we don't want to encourage developers to tailor their manifest for specific OS. 
Following this nice design philosophy doc from Matt - https://docs.google.com/document/d/1jn_qDJEWJTyCSt3uICYjXPWJaa5z-7HhfCRPQQ_sT78/edit#heading=h.mansal90qiqr

What about introducing `form_factor` for "narrow" and "wide", and separately considering removing platform?

**Comment by aarongustafson** [comment]
@philloooo I’m into it. Feel free to submit two PRs for this.
